CREATE TABLE IF NOT EXISTS nations (id varchar(10) NOT NULL, nation varchar(45),PRIMARY KEY (id));
INSERT INTO nations (id, nation) VALUES ("Z200","AFGHANISTAN");
INSERT INTO nations (id, nation) VALUES ("Z100","ALBANIA");
INSERT INTO nations (id, nation) VALUES ("Z301","ALGERIA");
INSERT INTO nations (id, nation) VALUES ("Z101","ANDORRA");
INSERT INTO nations (id, nation) VALUES ("Z302","ANGOLA");
INSERT INTO nations (id, nation) VALUES ("Z529","ANGUILLA (ISOLA)");
INSERT INTO nations (id, nation) VALUES ("Z532","ANTIGUA E BARBUDA");
INSERT INTO nations (id, nation) VALUES ("Z500","ANTILLE BRITANNICHE");
INSERT INTO nations (id, nation) VALUES ("Z521","ANTILLE BRITANNICHE");
INSERT INTO nations (id, nation) VALUES ("Z523","ANTILLE BRITANNICHE");
INSERT INTO nations (id, nation) VALUES ("Z501","ANTILLE OLANDESI");
INSERT INTO nations (id, nation) VALUES ("Z201","ARABIA MERIDIONALE FEDERAZIONE");
INSERT INTO nations (id, nation) VALUES ("Z202","ARABIA MERIDIONALE PROTETTORATO");
INSERT INTO nations (id, nation) VALUES ("Z203","ARABIA SAUDITA");
INSERT INTO nations (id, nation) VALUES ("Z600","ARGENTINA");
INSERT INTO nations (id, nation) VALUES ("Z137","ARMENIA");
INSERT INTO nations (id, nation) VALUES ("Z252","ARMENIA");
INSERT INTO nations (id, nation) VALUES ("Z700","AUSTRALIA");
INSERT INTO nations (id, nation) VALUES ("Z102","AUSTRIA");
INSERT INTO nations (id, nation) VALUES ("Z141","AZERBAIDJAN");
INSERT INTO nations (id, nation) VALUES ("Z253","AZERBAIDJAN");
INSERT INTO nations (id, nation) VALUES ("Z502","BAHAMAS");
INSERT INTO nations (id, nation) VALUES ("Z204","BAHREIN");
INSERT INTO nations (id, nation) VALUES ("Z249","BANGLADESH");
INSERT INTO nations (id, nation) VALUES ("Z522","BARBADOS");
INSERT INTO nations (id, nation) VALUES ("Z303","BASUTOLAND SUD AFRICA BRITANN");
INSERT INTO nations (id, nation) VALUES ("Z304","BECIUANIA SUD AFRICA BRITANNICO");
INSERT INTO nations (id, nation) VALUES ("Z103","BELGIO");
INSERT INTO nations (id, nation) VALUES ("Z512","BELIZE");
INSERT INTO nations (id, nation) VALUES ("Z314","BENIN");
INSERT INTO nations (id, nation) VALUES ("Z400","BERMUDA (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z205","BHUTAN");
INSERT INTO nations (id, nation) VALUES ("Z139","BIELORUSSIA=RUSSIA BIANCA");
INSERT INTO nations (id, nation) VALUES ("Z601","BOLIVIA");
INSERT INTO nations (id, nation) VALUES ("Z364","BOPHUTHATSWANA");
INSERT INTO nations (id, nation) VALUES ("Z153","BOSNIA ED ERZEGOVINA");
INSERT INTO nations (id, nation) VALUES ("Z358","BOTSWANA");
INSERT INTO nations (id, nation) VALUES ("Z602","BRASILE");
INSERT INTO nations (id, nation) VALUES ("Z207","BRUNEI");
INSERT INTO nations (id, nation) VALUES ("Z104","BULGARIA");
INSERT INTO nations (id, nation) VALUES ("Z354","BURKINA FASO");
INSERT INTO nations (id, nation) VALUES ("Z305","BURUNDI");
INSERT INTO nations (id, nation) VALUES ("Z208","CAMBOGIA");
INSERT INTO nations (id, nation) VALUES ("Z306","CAMERUN");
INSERT INTO nations (id, nation) VALUES ("Z401","CANADA");
INSERT INTO nations (id, nation) VALUES ("Z307","CAPO VERDE");
INSERT INTO nations (id, nation) VALUES ("Z701","CAROLINE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z530","CAYMAN (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z156","CECA REPUBBLICA");
INSERT INTO nations (id, nation) VALUES ("Z105","CECOSLOVACCHIA");
INSERT INTO nations (id, nation) VALUES ("Z308","CENTRAFRICANA REPUBBLICA");
INSERT INTO nations (id, nation) VALUES ("Z702","CHRISTMAS (ISOLA)");
INSERT INTO nations (id, nation) VALUES ("Z309","CIAD");
INSERT INTO nations (id, nation) VALUES ("Z603","CILE");
INSERT INTO nations (id, nation) VALUES ("Z217","CINA REPUBBLICA NAZIONALE=TAIWAN");
INSERT INTO nations (id, nation) VALUES ("Z210","CINA REPUBBLICA POPOLARE");
INSERT INTO nations (id, nation) VALUES ("Z211","CIPRO");
INSERT INTO nations (id, nation) VALUES ("Z367","CISKEI");
INSERT INTO nations (id, nation) VALUES ("Z106","CITTA' DEL VATICANO");
INSERT INTO nations (id, nation) VALUES ("Z212","COCOS (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z604","COLOMBIA");
INSERT INTO nations (id, nation) VALUES ("Z310","COMORE");
INSERT INTO nations (id, nation) VALUES ("Z370","CONGO BELGA");
INSERT INTO nations (id, nation) VALUES ("Z312","CONGO REPUBBLICA DEMOCRATICA");
INSERT INTO nations (id, nation) VALUES ("Z311","CONGO REPUBBLICA POPOLARE");
INSERT INTO nations (id, nation) VALUES ("Z703","COOK (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z214","COREA DEL NORD");
INSERT INTO nations (id, nation) VALUES ("Z213","COREA DEL SUD");
INSERT INTO nations (id, nation) VALUES ("Z313","COSTA D'AVORIO");
INSERT INTO nations (id, nation) VALUES ("Z503","COSTA RICA");
INSERT INTO nations (id, nation) VALUES ("Z149","CROAZIA");
INSERT INTO nations (id, nation) VALUES ("Z504","CUBA");
INSERT INTO nations (id, nation) VALUES ("Z107","DANIMARCA");
INSERT INTO nations (id, nation) VALUES ("Z900","DIPENDENZE AUSTRALIANE");
INSERT INTO nations (id, nation) VALUES ("Z901","DIPENDENZE BRITANNICHE");
INSERT INTO nations (id, nation) VALUES ("Z800","DIPENDENZE CANADESI");
INSERT INTO nations (id, nation) VALUES ("Z902","DIPENDENZE FRANCESI");
INSERT INTO nations (id, nation) VALUES ("Z903","DIPENDENZE NEOZELANDESI");
INSERT INTO nations (id, nation) VALUES ("Z904","DIPENDENZE NORVEGESI ANTARTICHE");
INSERT INTO nations (id, nation) VALUES ("Z801","DIPENDENZE NORVEGESI ARTICHE");
INSERT INTO nations (id, nation) VALUES ("Z802","DIPENDENZE SOVIETICHE");
INSERT INTO nations (id, nation) VALUES ("Z905","DIPENDENZE STATUNITENSI");
INSERT INTO nations (id, nation) VALUES ("Z906","DIPENDENZE SUDAFRICANE");
INSERT INTO nations (id, nation) VALUES ("Z361","DJIBOUTI");
INSERT INTO nations (id, nation) VALUES ("Z526","DOMINICA");
INSERT INTO nations (id, nation) VALUES ("Z505","DOMINICANA REPUBBLICA");
INSERT INTO nations (id, nation) VALUES ("Z605","ECUADOR");
INSERT INTO nations (id, nation) VALUES ("Z336","EGITTO");
INSERT INTO nations (id, nation) VALUES ("Z506","EL SALVADOR");
INSERT INTO nations (id, nation) VALUES ("Z215","EMIRATI ARABI UNITI");
INSERT INTO nations (id, nation) VALUES ("Z368","ERITREA");
INSERT INTO nations (id, nation) VALUES ("Z144","ESTONIA");
INSERT INTO nations (id, nation) VALUES ("Z315","ETIOPIA");
INSERT INTO nations (id, nation) VALUES ("Z108","FAER OER (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z704","FIGI=VITI");
INSERT INTO nations (id, nation) VALUES ("Z216","FILIPPINE");
INSERT INTO nations (id, nation) VALUES ("Z109","FINLANDIA");
INSERT INTO nations (id, nation) VALUES ("Z110","FRANCIA");
INSERT INTO nations (id, nation) VALUES ("Z316","GABON");
INSERT INTO nations (id, nation) VALUES ("Z317","GAMBIA");
INSERT INTO nations (id, nation) VALUES ("Z218","GAZA (TERRITORIO DI)");
INSERT INTO nations (id, nation) VALUES ("Z136","GEORGIA");
INSERT INTO nations (id, nation) VALUES ("Z254","GEORGIA");
INSERT INTO nations (id, nation) VALUES ("Z112","GERMANIA");
INSERT INTO nations (id, nation) VALUES ("Z111","GERMANIA REPUBBLICA DEMOCRATICA");
INSERT INTO nations (id, nation) VALUES ("Z318","GHANA");
INSERT INTO nations (id, nation) VALUES ("Z507","GIAMAICA");
INSERT INTO nations (id, nation) VALUES ("Z219","GIAPPONE");
INSERT INTO nations (id, nation) VALUES ("Z113","GIBILTERRA");
INSERT INTO nations (id, nation) VALUES ("Z705","GILBERT E ELLICE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z220","GIORDANIA");
INSERT INTO nations (id, nation) VALUES ("Z114","GRAN BRETAGNA E IRLANDA DEL NORD");
INSERT INTO nations (id, nation) VALUES ("Z115","GRECIA");
INSERT INTO nations (id, nation) VALUES ("Z524","GRENADA");
INSERT INTO nations (id, nation) VALUES ("Z402","GROENLANDIA");
INSERT INTO nations (id, nation) VALUES ("Z508","GUADALUPA");
INSERT INTO nations (id, nation) VALUES ("Z706","GUAM (ISOLA)");
INSERT INTO nations (id, nation) VALUES ("Z509","GUATEMALA");
INSERT INTO nations (id, nation) VALUES ("Z319","GUINEA");
INSERT INTO nations (id, nation) VALUES ("Z321","GUINEA EQUATORIALE");
INSERT INTO nations (id, nation) VALUES ("Z320","GUINEA-BISSAU");
INSERT INTO nations (id, nation) VALUES ("Z606","GUYANA");
INSERT INTO nations (id, nation) VALUES ("Z607","GUYANA=GUIANA FRANCESE");
INSERT INTO nations (id, nation) VALUES ("Z510","HAITI");
INSERT INTO nations (id, nation) VALUES ("Z511","HONDURAS");
INSERT INTO nations (id, nation) VALUES ("Z221","HONG KONG");
INSERT INTO nations (id, nation) VALUES ("Z323","IFNI");
INSERT INTO nations (id, nation) VALUES ("Z222","INDIA");
INSERT INTO nations (id, nation) VALUES ("Z223","INDONESIA");
INSERT INTO nations (id, nation) VALUES ("Z224","IRAN");
INSERT INTO nations (id, nation) VALUES ("Z225","IRAQ");
INSERT INTO nations (id, nation) VALUES ("Z707","IRIAN OCCIDENTALE");
INSERT INTO nations (id, nation) VALUES ("Z116","IRLANDA=EIRE");
INSERT INTO nations (id, nation) VALUES ("Z117","ISLANDA");
INSERT INTO nations (id, nation) VALUES ("Z721","ISOLE CILENE (PASQUA E SALA Y GOMEZ)");
INSERT INTO nations (id, nation) VALUES ("Z226","ISRAELE");
INSERT INTO nations (id, nation) VALUES ("ITA","ITALIA");
INSERT INTO nations (id, nation) VALUES ("Z118","JUGOSLAVIA");
INSERT INTO nations (id, nation) VALUES ("Z152","KAZAKHISTAN");
INSERT INTO nations (id, nation) VALUES ("Z255","KAZAKHISTAN");
INSERT INTO nations (id, nation) VALUES ("Z322","KENYA");
INSERT INTO nations (id, nation) VALUES ("Z142","KIRGHIZISTAN");
INSERT INTO nations (id, nation) VALUES ("Z256","KIRGHIZISTAN");
INSERT INTO nations (id, nation) VALUES ("Z731","KIRIBATI");
INSERT INTO nations (id, nation) VALUES ("Z160","KOSSOVO");
INSERT INTO nations (id, nation) VALUES ("Z227","KUWAIT");
INSERT INTO nations (id, nation) VALUES ("Z324","LA REUNION (ISOLA)");
INSERT INTO nations (id, nation) VALUES ("Z228","LAOS");
INSERT INTO nations (id, nation) VALUES ("Z359","LESOTHO");
INSERT INTO nations (id, nation) VALUES ("Z145","LETTONIA");
INSERT INTO nations (id, nation) VALUES ("Z229","LIBANO");
INSERT INTO nations (id, nation) VALUES ("Z325","LIBERIA");
INSERT INTO nations (id, nation) VALUES ("Z326","LIBIA");
INSERT INTO nations (id, nation) VALUES ("Z119","LIECHTENSTEIN");
INSERT INTO nations (id, nation) VALUES ("Z146","LITUANIA");
INSERT INTO nations (id, nation) VALUES ("Z120","LUSSEMBURGO");
INSERT INTO nations (id, nation) VALUES ("Z231","MACAO");
INSERT INTO nations (id, nation) VALUES ("Z148","MACEDONIA");
INSERT INTO nations (id, nation) VALUES ("Z708","MACQUARIE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z327","MADAGASCAR");
INSERT INTO nations (id, nation) VALUES ("Z328","MALAWI");
INSERT INTO nations (id, nation) VALUES ("Z230","MALAYSIA");
INSERT INTO nations (id, nation) VALUES ("Z247","MALAYSIA");
INSERT INTO nations (id, nation) VALUES ("Z232","MALDIVE");
INSERT INTO nations (id, nation) VALUES ("Z329","MALI");
INSERT INTO nations (id, nation) VALUES ("Z121","MALTA");
INSERT INTO nations (id, nation) VALUES ("Z609","MALVINE=FALKLAND (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z122","MAN (ISOLA)");
INSERT INTO nations (id, nation) VALUES ("Z709","MARCUS (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z710","MARIANNE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z330","MAROCCO");
INSERT INTO nations (id, nation) VALUES ("Z711","MARSHALL  (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z513","MARTINICA");
INSERT INTO nations (id, nation) VALUES ("Z331","MAURITANIA");
INSERT INTO nations (id, nation) VALUES ("Z332","MAURITIUS (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z360","MAYOTTE (ISOLA)");
INSERT INTO nations (id, nation) VALUES ("Z514","MESSICO");
INSERT INTO nations (id, nation) VALUES ("Z735","MICRONESIA STATI FEDERATI");
INSERT INTO nations (id, nation) VALUES ("Z712","MIDWAY (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z140","MOLDAVIA");
INSERT INTO nations (id, nation) VALUES ("Z123","MONACO");
INSERT INTO nations (id, nation) VALUES ("Z233","MONGOLIA");
INSERT INTO nations (id, nation) VALUES ("Z159","MONTENEGRO");
INSERT INTO nations (id, nation) VALUES ("Z531","MONTSERRAT");
INSERT INTO nations (id, nation) VALUES ("Z333","MOZAMBICO");
INSERT INTO nations (id, nation) VALUES ("Z206","MYANMAR (BIRMANIA)");
INSERT INTO nations (id, nation) VALUES ("Z300","NAMIBIA");
INSERT INTO nations (id, nation) VALUES ("Z713","NAURU");
INSERT INTO nations (id, nation) VALUES ("Z234","NEPAL");
INSERT INTO nations (id, nation) VALUES ("Z515","NICARAGUA");
INSERT INTO nations (id, nation) VALUES ("Z334","NIGER");
INSERT INTO nations (id, nation) VALUES ("Z335","NIGERIA");
INSERT INTO nations (id, nation) VALUES ("Z714","NIUE=SAVAGE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z715","NORFOLK (ISOLE E ISOLE DEL MAR DEI CORAL");
INSERT INTO nations (id, nation) VALUES ("Z124","NORMANNE (ISOLE)=ISOLE DEL CANALE");
INSERT INTO nations (id, nation) VALUES ("Z125","NORVEGIA");
INSERT INTO nations (id, nation) VALUES ("Z716","NUOVA CALEDONIA (ISOLE E DIPENDENZE)");
INSERT INTO nations (id, nation) VALUES ("Z718","NUOVA GUINEA");
INSERT INTO nations (id, nation) VALUES ("Z719","NUOVA ZELANDA");
INSERT INTO nations (id, nation) VALUES ("Z717","NUOVE EBRIDI (ISOLE CONDOMINIO FRANCO-IN");
INSERT INTO nations (id, nation) VALUES ("Z369","NYASALAND");
INSERT INTO nations (id, nation) VALUES ("Z235","OMAN");
INSERT INTO nations (id, nation) VALUES ("Z126","PAESI BASSI");
INSERT INTO nations (id, nation) VALUES ("Z236","PAKISTAN");
INSERT INTO nations (id, nation) VALUES ("Z734","PALAU");
INSERT INTO nations (id, nation) VALUES ("Z516","PANAMA");
INSERT INTO nations (id, nation) VALUES ("Z517","PANAMA ZONA DEL CANALE");
INSERT INTO nations (id, nation) VALUES ("Z730","PAPUA NUOVA GUINEA");
INSERT INTO nations (id, nation) VALUES ("Z720","PAPUASIA");
INSERT INTO nations (id, nation) VALUES ("Z610","PARAGUAY");
INSERT INTO nations (id, nation) VALUES ("Z611","PERU'");
INSERT INTO nations (id, nation) VALUES ("Z722","PITCAIRN (E DIPENDENZE)");
INSERT INTO nations (id, nation) VALUES ("Z723","POLINESIA FRANCESE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z127","POLONIA");
INSERT INTO nations (id, nation) VALUES ("Z128","PORTOGALLO");
INSERT INTO nations (id, nation) VALUES ("Z518","PUERTO RICO");
INSERT INTO nations (id, nation) VALUES ("Z237","QATAR");
INSERT INTO nations (id, nation) VALUES ("Z129","ROMANIA");
INSERT INTO nations (id, nation) VALUES ("Z338","RUANDA");
INSERT INTO nations (id, nation) VALUES ("Z154","RUSSIA=FEDERAZIONE RUSSA");
INSERT INTO nations (id, nation) VALUES ("Z238","RYUKYU (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z362","SAHARA MERIDIONALE");
INSERT INTO nations (id, nation) VALUES ("Z363","SAHARA SETTENTRIONALE");
INSERT INTO nations (id, nation) VALUES ("Z339","SAHARA SPAGNOLO");
INSERT INTO nations (id, nation) VALUES ("Z533","SAINT KITTS E NEVIS=SAINT CHRISTOPHER E");
INSERT INTO nations (id, nation) VALUES ("Z527","SAINT LUCIA");
INSERT INTO nations (id, nation) VALUES ("Z403","SAINT PIERRE ET MIQUELON (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z528","SAINT VINCENT E GRENADINE");
INSERT INTO nations (id, nation) VALUES ("Z724","SALOMONE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z726","SAMOA (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z725","SAMOA AMERICANE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z130","SAN MARINO");
INSERT INTO nations (id, nation) VALUES ("Z340","SANT'ELENA (ISOLA)");
INSERT INTO nations (id, nation) VALUES ("Z341","SAO TOME E PRINCIPE");
INSERT INTO nations (id, nation) VALUES ("Z343","SENEGAL");
INSERT INTO nations (id, nation) VALUES ("Z158","SERBIA");
INSERT INTO nations (id, nation) VALUES ("Z157","SERBIA E MONTENEGRO");
INSERT INTO nations (id, nation) VALUES ("Z342","SEYCHELLES");
INSERT INTO nations (id, nation) VALUES ("Z344","SIERRA LEONE");
INSERT INTO nations (id, nation) VALUES ("Z239","SIKKIM");
INSERT INTO nations (id, nation) VALUES ("Z248","SINGAPORE");
INSERT INTO nations (id, nation) VALUES ("Z240","SIRIA");
INSERT INTO nations (id, nation) VALUES ("Z155","SLOVACCHIA");
INSERT INTO nations (id, nation) VALUES ("Z150","SLOVENIA");
INSERT INTO nations (id, nation) VALUES ("Z345","SOMALIA");
INSERT INTO nations (id, nation) VALUES ("Z346","SOMALIA FRANCESE");
INSERT INTO nations (id, nation) VALUES ("Z131","SPAGNA");
INSERT INTO nations (id, nation) VALUES ("Z209","SRI LANKA");
INSERT INTO nations (id, nation) VALUES ("Z404","STATI UNITI D'AMERICA");
INSERT INTO nations (id, nation) VALUES ("Z907","SUD SUDAN");
INSERT INTO nations (id, nation) VALUES ("Z347","SUDAFRICANA REPUBBLICA");
INSERT INTO nations (id, nation) VALUES ("Z348","SUDAN");
INSERT INTO nations (id, nation) VALUES ("Z608","SURINAME");
INSERT INTO nations (id, nation) VALUES ("Z132","SVEZIA");
INSERT INTO nations (id, nation) VALUES ("Z133","SVIZZERA");
INSERT INTO nations (id, nation) VALUES ("Z349","SWAZILAND");
INSERT INTO nations (id, nation) VALUES ("Z147","TAGIKISTAN");
INSERT INTO nations (id, nation) VALUES ("Z257","TAGIKISTAN");
INSERT INTO nations (id, nation) VALUES ("Z350","TANGANICA");
INSERT INTO nations (id, nation) VALUES ("Z357","TANZANIA");
INSERT INTO nations (id, nation) VALUES ("Z161","TERRITORI PALESTINESI");
INSERT INTO nations (id, nation) VALUES ("Z241","THAILANDIA");
INSERT INTO nations (id, nation) VALUES ("Z242","TIMOR (ISOLA)");
INSERT INTO nations (id, nation) VALUES ("Z351","TOGO");
INSERT INTO nations (id, nation) VALUES ("Z727","TOKELAU=ISOLE DELL'UNIONE");
INSERT INTO nations (id, nation) VALUES ("Z728","TONGA=ISOLE DEGLI AMICI");
INSERT INTO nations (id, nation) VALUES ("Z365","TRANSKEI");
INSERT INTO nations (id, nation) VALUES ("Z612","TRINIDAD E TOBAGO");
INSERT INTO nations (id, nation) VALUES ("Z352","TUNISIA");
INSERT INTO nations (id, nation) VALUES ("Z243","TURCHIA");
INSERT INTO nations (id, nation) VALUES ("Z151","TURKMENISTAN");
INSERT INTO nations (id, nation) VALUES ("Z258","TURKMENISTAN");
INSERT INTO nations (id, nation) VALUES ("Z519","TURKS E CAICOS (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z732","TUVALU");
INSERT INTO nations (id, nation) VALUES ("Z138","UCRAINA");
INSERT INTO nations (id, nation) VALUES ("Z353","UGANDA");
INSERT INTO nations (id, nation) VALUES ("Z134","UNGHERIA");
INSERT INTO nations (id, nation) VALUES ("Z135","UNIONE REPUBBLICHE SOCIALISTE SOVIETICHE");
INSERT INTO nations (id, nation) VALUES ("Z613","URUGUAY");
INSERT INTO nations (id, nation) VALUES ("Z143","UZBEKISTAN");
INSERT INTO nations (id, nation) VALUES ("Z259","UZBEKISTAN");
INSERT INTO nations (id, nation) VALUES ("Z733","VANUATU");
INSERT INTO nations (id, nation) VALUES ("Z366","VENDA");
INSERT INTO nations (id, nation) VALUES ("Z614","VENEZUELA");
INSERT INTO nations (id, nation) VALUES ("Z520","VERGINI AMERICANE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z525","VERGINI BRITANNICHE (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z251","VIETNAM");
INSERT INTO nations (id, nation) VALUES ("Z245","VIETNAM DEL NORD");
INSERT INTO nations (id, nation) VALUES ("Z244","VIETNAM DEL SUD");
INSERT INTO nations (id, nation) VALUES ("Z729","WALLIS E FUTUNA (ISOLE)");
INSERT INTO nations (id, nation) VALUES ("Z246","YEMEN");
INSERT INTO nations (id, nation) VALUES ("Z250","YEMEN REP. DEM. POPOLARE");
INSERT INTO nations (id, nation) VALUES ("Z355","ZAMBIA");
INSERT INTO nations (id, nation) VALUES ("Z356","ZANZIBAR");
